---
- name : Address Group Object Modification
  hosts: '{{hosts}}'
  gather_facts: false
  connection: local
  collections:
    - paloaltonetworks.panos
    
  vars:
    devices: []
    
  tasks:

  - name: Iterate over the hosts
    set_fact:
      devices: "{{ devices | default(omit) + [item]}}"
    with_inventory_hostnames: 
      - domain-controllers
    register: host
    
  - name: print hosts list
    debug:
      msg: '{{ devices}}'
    
 
  - name: Create Devices list
    set_fact: 
      devices1: hosts.hostnames
      

      
  - name: Create/Modify Address Group Object Domain-Controllers
    panos_address_group:
      provider: '{{ provider }}'
      name: 'DomainControllers'
      static_value: '{{devices}}'
      device_group: 'shared'
    register: result
    
  - name: Assert Modify was successful
    assert: 
      that:
        - result is success
        - result is changed
        
  - name: Commit the Changes
    panos_commit: 
      provider: '{{provider}}'
    register: result
    
  - name: Assert Commit was successful
    assert: 
      that:
        - result is success
    
    
     
      
    
    
