---
- name : Address Group Object Modification
  hosts: localhost
  gather_facts: false
  connection: local
  collections:
    - paloaltonetworks.panos
    
  vars:
    devices: []
    
  tasks:

  - name: Iterate over the hosts
    set_fact:
      devices: "{{ devices | default(omit) + [item]}}"
    with_inventory_hostnames: 
      - domain-controllers
    register: host
    
  - name: print hosts list
    debug:
      msg: '{{ devices}}'
    
 
  - name: Create Devices list
    set_fact: 
      devices1: hosts.hostnames
      
  - name: Add test pre-rule to Panorama
    panos_security_rule:
      provider: '{{ provider }}'
      rule_name: 'Ansible test 1'
      description: 'An Ansible test pre-rule'
      source_zone: ['internal']
      destination_zone: ['external']
      source_ip: ['1.2.3.4']
      source_user: ['any']
      destination_ip: ['any']
      category: ['any']
      application: ['any']
      service: ['service-http']
      hip_profiles: ['any']
      action: 'allow'
      device_group: 'shared'
      commit: False
      
      
  - name: Create/Modify Address Group Object Domain-Controllers
    panos_address_group:
      provider: '{{ provider }}'
      name: 'Domain-Controllers'
      static_value: '{{devices}}'
      device_group: '{{device_group | default(omit)}}'
      tag: ['DC']
    register: result
    
  - name: Assert Modify was successful
    assert: 
      that:
        - result is success
        - result is changed
        
  - name: Commit the Changes
    panos_commit: 
      provider: '{{provider}}'
    register: result
    
  - name: Assert Commit was successful
    assert: 
      that:
        - result is success
    
    
     
      
    
    
