---
- name : Address Group Object Modification
  hosts: '{{hosts}}'
  gather_facts: false
  connection: httpapi
  collections:
    - paloaltonetworks.panos
    
  vars:
    devices: []
    ansible_network_os: paloaltonetworks.panos.panos
    ansible_httpapi_use_ssl: yes
    ansible_httpapi_validate_certs: no
    ansible_httpapi_port: 443
    
  tasks:    

  - debug:
      var: groups.keys()
 
  - name: Create/Update Address Group objects 
    include_tasks: create_update_AddressGroup.yaml
    loop: "{{ groups.keys()| reject('search','all') | reject('search','ungrouped') | list}}"
    loop_control:
      loop_var: address_group
      

      
  - name: Commit the Changes
    panos_commit: 
      provider: '{{provider}}'
    register: result
    
  - name: Assert Commit was successful
    assert: 
      that:
        - result is success
    
    
     
      
    
    
