---
- name : Address Group Object Modification
  hosts: localhost
  gather_facts: false
  connection: local
  collections:
    - paloaltonetworks.panos
    
  tasks:

  - name: Iterate over the hosts
    debug:
      msg: '{{ item}}'
    with_inventory_hostnames: 
      - domain-controllers
    register: hosts
    
  - name: print hosts
    debug:
      var: '{{ hosts}}'
    
 
  - name: Create Devices list
    set_fact: 
      devices: hosts.hostnames
      
  - name: Create/Modify Address Group Object Domain-Controllers
    panos_address_group:
      provider: '{{ provider }}'
      name: 'Domain-Controllers'
      static_value: devices
      device_group: '{{device_group | default(omit)}}'
      tag: ['DC']
    register: result
    
  - name: Assert Modify was successful
    assert: 
      that:
        - result is success
        - result is changed
        
  - name: Commit the Changes
    panos_commit: 
      provider: '{{provider}}'
    register: result
    
  - name: Assert Commit was successful
    assert: 
      that:
        - result is success
    
    
     
      
    
    
