# This is a basic workflow to help you get started with Actions

name: Update Address Group

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths: 
      - domain-controllers.yaml
  pull_request:
    branches: [ main ]
    paths: 
      - domain-controllers.yaml
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Play Ansible Playbook
        uses: arillso/action.playbook@master
        with:
          playbook: /github/workspace/main.yaml
          inventory: /github/workspace/Inventory/hosts.ini
          galaxy_file: /github/workspace/collections/requirements.yaml
          extra_vars: "hosts=localhost"
        env:
          ANSIBLE_HOST_KEY_CHECKING: 'false'
          ANSIBLE_DEPRECATION_WARNINGS: 'false'

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          
      - name: Run Ansible playbook
        # You may pin to the exact commit or the version.
        # uses: dawidd6/action-ansible-playbook@671974ed60e946e11964cb0c26e69caaa4b1f559
        uses: dawidd6/action-ansible-playbook@v2.5.0
        with:
          # Ansible playbook filepath
          playbook: /github/workspace/main.yaml
    # Ansible Galaxy requirements filepath
          requirements: /github/workspace/collections/requirements.yaml # optional
          inventory: /github/workspace/Inventory/hosts.ini # optional
    # Extra options that should be passed to ansible-playbook command
        #  options: -e 'hosts=localhost' # optional
    
